### ISSUE TITLE
Why are you hoarding so many crates.io names?

### ISSUE THREAD

**Issue by WiSaGaN** [hilbert-space/metal#1]

**Comment by IvanUkhov** [comment]
I have/had big plans. If you need one of the names, explain what for. I’ll be more than happy to give it to you if it’s for a good reason. Thanks!

**Comment by WiSaGaN** [comment]
I don't mind thinking up some other names. Just a bit surprised to see so many crates name occupied with no code.

**Comment by IvanUkhov** [comment]
Well, some of them are my old projects, which I renamed or deprecated in favor of other crates. Some I reserved because I have certain interests, and I’m planning to those names. This company account is sort of my personal drawer/trash bin.

**Comment by WiSaGaN** [comment]
Hope you can make progress on those projects then.
