### ISSUE TITLE
Unused crate name

### ISSUE THREAD

**Issue by grovesNL** [hilbert-space/metal#4]
As mentioned in the README:

> This crate is unused. It will be handed over if anybody has a good use for the name.

We have a fairly active crate (currently published with the name [`metal-rs`](https://crates.io/crates/metal-rs)) used to provide bindings for [Apple's Metal](https://developer.apple.com/metal/) graphics API. Would we be able to use this crate name?

**Comment by grovesNL** [comment]
Great, thank you! It would be great if you could transfer the ownership to @kvark (https://crates.io/users/kvark).

**Comment by IvanUkhov** [comment]
Done. Dzmitry should have received an invite.
